language: node_js
node_js:
 - 'node'
 - '10'
script:
- npm run all
deploy:
  provider: npm
  email: git_nikku@nixis.de
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: nikku/karma-browserify
