language: node_js
node_js:
 - 'node'
 - '10'
 - '8'
script:
- npm run all
before_install:
  - if [[ `node -v` == v8* ]]; then npm i -g npm@latest-5; fi
  - if [[ `node -v` != v8* ]]; then npm i -g npm@latest-6; fi
deploy:
  provider: npm
  email: git_nikku@nixis.de
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: nikku/karma-browserify
